name: food_delivery_app
description: food_delivery_app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+1

environment:
  sdk: '>=2.12.2 <4.0.0'
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.5
  #google_maps_flutter: ^2.2.6
  google_maps_place_picker_mb:
    git:
      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
      ref: 2.0.0-mb.22
  mvc_pattern: ^8.12.0
  global_configuration: ^2.0.0
  #html: ^0.15.4
  shared_preferences: ^2.2.3
  #flutter_html: ^2.2.1
  flutter_svg:
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  cached_network_image:
  fluttertoast: ^8.0.5
  intl_utils:
  carousel_slider:
  firebase_core: ^2.7.0
  firebase_messaging: ^14.4.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.0
  #flutter_local_notifications: ^5.0.0
  flutter_otp_text_field:
  tab_indicator_styler:
  cloud_firestore:
  flutter_rating_bar:
  table_calendar:
  share:
  marquee:
  geolocator: ^9.0.1
  geocoding: ^2.0.2
  flutter_launcher_icons:
  translator:
  html_unescape:
  restart_app:
  file_picker:
  coupon_uikit:
  flutter_stripe: ^7.0.0
  flutter_dotenv:
  intl_phone_field: ^3.2.0
  connectivity:
  google_maps_flutter: ^2.6.1
  intl:
  shimmer:
  flutter_local_notifications:
 # uuid:
  image_picker: ^1.1.2
  dotted_border:
  flutter_phoenix:
  flutter_image_slideshow:
  permission_handler:
  google_fonts: ^6.2.1
  freshchat_sdk:
  clipboard:
  location:
  flutter_inappwebview: ^5.3.2
  html: ^0.15.0
  change_app_package_name: ^1.2.0







flutter_icons:
  image_path: "assets/img/HOME-FOOD-LOGO2.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_staggered_grid_view:
  intl:
  http:
  quiver:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/
    - assets/img/image-Ae.png
    - assets/.env


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true